### ISSUE TITLE
undefined filter param on wrhs.assets.get is not omitted

### ISSUE THREAD

**Issue by gingur** [warehouseai/warehouse.ai-api-client#14]
## 🐛 Bug Report
Using `wrhs.assets.get` without a `filter` param, it defaults to `undefined`. This value is making it's way through to the requested URL and causing zero results to come back.

## To Reproduce
`wrhs.assets.get({ env, pkg }, (err, res) => ... )`
returns err as `null` and res as  `{ files: [] }`.

## Expected Behavior
Should return all results

**Comment by msluther** [comment]
Resolved by #15
